core/urls.py
from django.urls import path
from house import views as house_views

app_name = "core"
urlpatterns = [
    path("", house_views.HomeView.as_view(), name="home"),
    # path("", house_views.all_houses)
]

house/urls.py
from django.urls import path
from . import views 

app_name = "houses"
urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("<int:pk>", views.HouseDetail.as_view(), name="detail"),
    path("create/", views.CreateHouseView.as_view(), name="create"),
    path("<int:pk>/edit/", views.EditHouseView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.HousePhotosView.as_view(), name="photos"),
    path(
        "<int:house_pk>/photos/<int:photo_pk>/delete/",
        views.delete_photo,
        name="delete-photo",
    ),
    path("<int:pk>/photos/add", views.AddPhotoView.as_view(), name="add-photos"),
    path("search/", views.SearchView.as_view(), name="search"),
]

landbnb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("admin/", admin.site.urls),
    path("users/", include("users.urls", namespace="users")),
    path("houses/", include("house.urls", namespace="houses")),
    path("reservations/", include("reservation.urls", namespace="reservations")),
    path("reviews/", include("review.urls", namespace="reviews")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include
from . import views

app_name = "users"
urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github/", views.github_login, name="github-login"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
    path("switch-hosting/", views.switch_hosting, name="switch-hosting"),
    # path("verify/<str:key>", views.complete_verification, name="complete-verification"),
]

templates/partials/footer.html
{% load i18n %}
<footer class="container mx-auto text-center py-10 border-t font-medium text-gray-500">
    <div class="flex flex-col">
        <span>&copy; 2022 LandBnB, {% trans "All rights reserved" %}.</span>
    </div>
    {% comment %} <div class="mt-10 flex">
        {% get_current_language as LANGUAGE_CODE %}
        <select class="w-1/5 h-8" id="js-lang">
            <option value="en"
                {% if LANGUAGE_CODE == 'en' %}
                selected
                {% endif %}
            >English</option>
            <option value="vn"
                {% if LANGUAGE_CODE == 'vn' %}
                    selected
                {% endif %}
            >Vietnamese</option>
        </select>
    </div> {% endcomment %}
</footer>

templates/partials/header.html
<header>
    <a href="/"> LandBnB </a>
    <ul>
        <li><a href="#"> Login </a> </li>
    </ul>
</header>

templates/partials/messages.html
{% if messages %}
<ul class="absolute top-0 mx-auto left-0 right-0 flex justify-center">
    {% for message in messages %}
    <li class="message font-medium bg-gray-700 z-10 rounded-full text-white py-4 px-6 w-64 text-center {% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

templates/partials/nav.html
<a href="{% url "core:home" %}">LandBnB</a>
    <ul class="flex items-center text-sm font-medium h-full">
        {% if user.is_authenticated %}
            <li class="nav_link">
                <a href="{% url 'users:switch-hosting' %}">
                    {% if request.session.is_hosting %}
                        Stop hosting
                    {% else %}
                        Start hosting
                    {% endif %}
                </a>
            </li>
            {% if request.session.is_hosting %}
                <li class="nav_link"><a href="{% url 'houses:create' %}">Add a house</a></li>
            {% endif %}        
            <li class="nav_link"><a href="{{user.get_absolute_url}}">Profile</a></li>
            <li class="nav_link"><a href="{% url "users:logout" %}">Log out</a></li>
        {% else %}
            <li class="nav_link"><a href="{% url "users:login" %}">Log in</a></li>
            <li class="nav_link"><a href="{% url "users:signup" %}">Register</a></li>
        {% endif %}    
    </ul>

templates/partials/social_login.html
<div>
    <a href="{% url 'users:gith-login' %}">
        Continue with Github
    </a>
</div>