core/urls.py
from django.urls import path
from house import views as house_views

app_name = "core"
urlpatterns = [
    path("", house_views.HomeView.as_view(), name="home"),
    # path("", house_views.all_houses)
]

house/urls.py
from django.urls import path
from . import views 

app_name = "houses"
urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("<int:pk>", views.HouseDetail.as_view(), name="detail"),
    path("create/", views.CreateHouseView.as_view(), name="create"),
    path("<int:pk>/edit/", views.EditHouseView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.HousePhotosView.as_view(), name="photos"),
    path(
        "<int:house_pk>/photos/<int:photo_pk>/delete/",
        views.delete_photo,
        name="delete-photo",
    ),
    path("<int:pk>/photos/add", views.AddPhotoView.as_view(), name="add-photos"),
    path("search/", views.SearchView.as_view(), name="search"),
]

landbnb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("admin/", admin.site.urls),
    path("users/", include("users.urls", namespace="users")),
    path("houses/", include("house.urls", namespace="houses")),
    path("reservations/", include("reservation.urls", namespace="reservations")),
    path("reviews/", include("review.urls", namespace="reviews")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

house/models.py
from django.db import models
from django.utils import timezone
from django.utils.text import Truncator
from django_countries.fields import CountryField
from django.urls import reverse
from cal import Calendar
from core import models as core_models

# Create your models here.
class TimeStampedModel(models.Model):
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateField(auto_now=True)
    class Meta:
        abstract = True

class Photo(core_models.TimeStampedModel):
    caption = models.CharField(max_length=80)
    file = models.ImageField()
    house = models.ForeignKey("House", related_name="photo", on_delete=models.CASCADE)

class AbstractItem(core_models.TimeStampedModel):
    # Define abstract object
    name = models.CharField(max_length=150)
    class Meta:
        abstract = True
    def __str__(self) -> str:
        return self.name

class Amenity(AbstractItem):
    class Meta:
        verbose_name_plural = "Amenities"

class HouseType(AbstractItem):
    class Meta:
        verbose_name = "House type"

class Facility(AbstractItem):
    class Meta:
        verbose_name_plural = "Facilities"

class Photo(core_models.TimeStampedModel):
    caption = models.CharField(max_length=80)
    file = models.ImageField(upload_to="house_photos",)
    house = models.ForeignKey("House", related_name="photos", on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.caption

class House(models.Model):
    # id = models.IntegerField()
    name = models.TextField(max_length=100)
    description = models.TextField()

    country = CountryField()
    city = models.CharField(max_length=30)

    price = models.IntegerField(default=0)

    address = models.TextField(max_length=100, default='abc')

    guest = models.IntegerField(default=0)
    bedroom = models.IntegerField(default=0)
    bed = models.IntegerField(default=0)
    bathroom = models.IntegerField(default=0)

    check_in = models.TimeField(null=True)
    check_out = models.TimeField(null=True)

    host = models.ForeignKey("users.User", related_name="houses", on_delete=models.CASCADE, null=True)
    house_type =models.ForeignKey("HouseType", verbose_name="House type", related_name="houses", on_delete=models.CASCADE, null=True, blank=True)

    amenities = models.ManyToManyField("Amenity", related_name="houses", blank=True)
    facilities = models.ManyToManyField("Facility", related_name="houses", blank=True)        

    def __str__(self):
        return self.name

    def amenities_count(self):
        # return "\n".join([ame.amenity for ame in self.amenities.all()])
        return self.amenities.count()
    amenities_count.short_description = "amenity"

    def first_photo(self):
        try:
            (photo,) = self.photos.all()[:1]
            return photo.file.url
        except ValueError:
            return None
    
    def get_next_four_photos(self):
        photos = self.photos.all()[1:5]
        return photos

    def get_calendars(self):
        now = timezone.now()
        this_year = now.year
        this_month = now.month
        next_month = this_month + 1
        if this_month == 12:
            next_month = 1
        this_month_cal = Calendar(this_year, this_month)
        next_month_cal = Calendar(this_year, next_month)
        return [this_month_cal, next_month_cal]

    def total_rating(self):
        all_reviews = self.reviews.all()
        all_rating = 0
        if len(all_reviews) > 0:
            for review in all_reviews:
                all_rating += review.avgRating()
            return round(all_rating/len(all_reviews), 2)
        return 0
    total_rating.short_description = "rating"

    def truncated_description(self):
        return Truncator(self.description).words(10, truncate='...')

    def save_city(self, *args, **kwargs):
        self.city = str.capitalize(self.city)
        super().save_city(*args, **kwargs)
    
    def get_absolute_url(self):
        return reverse("houses: detail", kwargs={"pk": self.pk})
    

house/forms.py
from django import forms
from django_countries.fields import CountryField
from . import models

class SearchForm(forms.Form):
    country = CountryField(blank=True).formfield()
    city = forms.CharField(initial="", required=False)
    house_type = forms.ModelChoiceField(
        empty_label="Any kind", queryset=models.HouseType.objects.all(),
        required=False
    )
    price = forms.IntegerField(required=False)
    guests = forms.IntegerField(required=False)
    bedrooms = forms.IntegerField(required=False)
    beds = forms.IntegerField(required=False)
    baths = forms.IntegerField(required=False)

    amenities = forms.ModelMultipleChoiceField(
        queryset=models.Amenity.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )
    facilities = forms.ModelMultipleChoiceField(
        queryset=models.Facility.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )

class CreateHouseForm(forms.ModelForm):
    class Meta:
        model = models.House
        fields = (
            "name",
            "description",
            "country",
            "city",
            "price",
            "address",
            "guest",
            "bed",
            "bedroom",
            "bathroom",
            "check_in",
            "check_out",
            "house_type",
            "amenities",
            "facilities",
        )
    
    def save(self, *args, **kwargs):
        house = super().save(commit=False) 
        return house

class CreatePhotoForm(forms.ModelForm): 
    class Meta:
        model = models.Photo
        fields = ("caption", "file")
    def save(self, pk, *args, **kwargs):
        photo = super().save(commit=False)

        house = models.House.objects.get(pk=pk)
        photo.house = house 
        photo.save()

house/views.py
from django.shortcuts import render, redirect, reverse
from django.utils import timezone
from . import models, forms
from django.core.paginator import Paginator
from django.views.generic import ListView, DetailView, View, UpdateView, FormView
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django_countries import countries
from users import mixin as user_mixins
from django.http import Http404

# Create your views here.

class HomeView(ListView):
    model = models.House
    paginate_by = 10
    paginate_orphans = 5
    ordering = "name"
    # ordering = "created"
    page_kwarg = "page" 
    context_object_name = "houses"

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     now = timezone.now
    #     context["now"] = now
        
    #     return context
    # pass

class HouseDetail(DetailView):
    model = models.House

class SearchView(View):
    def get(self, request):
        country = request.GET.get("country")
        houses = models.House.objects.all()
        if country:
            form = forms.SearchForm(request.GET)
            if form.is_valid():
                country = form.cleaned_data.get("country")
                city = form.cleaned_data.get("city")
                house_type = form.cleaned_data.get("house_type")
                price = form.cleaned_data.get("price")
                guests = form.cleaned_data.get("guests")
                bedrooms = form.cleaned_data.get("bedrooms")
                beds = form.cleaned_data.get("beds")
                baths = form.cleaned_data.get("baths")
                amenities = form.cleaned_data.get("amenities")
                facilities = form.cleaned_data.get("facilities")

                # search argument
                filter_args = {}
                filter_args["country"] = country
                if city != "":
                    filter_args["city__startswith"] = city
                if house_type is not None:
                    filter_args["house_type"] = house_type
                if price is not None:
                    filter_args["price__lte"] = price
                if guests is not None:
                    filter_args["guests__gte"] = guests
                if bedrooms is not None:
                    filter_args["bedrooms__gte"] = bedrooms
                if beds is not None:
                    filter_args["beds__gte"] = beds
                if baths is not None:
                    filter_args["baths__gte"] = baths
                for amenity in amenities:
                    filter_args["amenities"] = amenity
                for facility in facilities:
                    filter_args["facilities"] = facility

                qs = models.House.objects.filter(**filter_args)
                paginator = Paginator(qs, 10, orphans=5)
                page = request.GET.get("page", 1)
                houses = paginator.get_page(page)
                context = {"form": form, "houses": houses}
                return render(request, "house/search.html", context)
        else:
            form = forms.SearchForm()
            context = {"form": form}

        # context = {"form": form, "houses":houses} 

        return render(request, "house/search.html", context)

class CreateHouseView(user_mixins.LoggedInOnlyView, FormView):
    form_class = forms.CreateHouseForm 
    template_name = "house/house_create.html"

    def form_valid(self, form):
        house = form.save() 
        house.host = self.request.user  
        house.save()  
        form.save_m2m() # many 2 many
        messages.success(self.request, "House has been added")
        return redirect(reverse("houses:detail", kwargs={"pk": house.pk}))

class EditHouseView(user_mixins.LoggedInOnlyView, UpdateView): 
    model = models.House 
    template_name = "house/house_edit.html" 
    fields = ( 
        "name",
        "description",
        "country",
        "city",
        "price",
        "address",
        "guest",
        "bed",
        "bedroom",
        "bathroom",
        "check_in",
        "check_out",
        "house_type",
        "amenities",
        "facilities",
    )
    def get_object(self, queryset=None):
        house = super().get_object(queryset=queryset)
        if house.host.pk != self.request.user.pk:
            raise Http404()
        return house

class HousePhotosView(user_mixins.LoggedInOnlyView, DetailView):
    model = models.House
    template_name = "house/house_photos.html"
    def get_object(self, queryset=None):  
        house = super().get_object(queryset=queryset)
        if house.host.pk != self.request.user.pk:
            raise Http404()
        return house

class AddPhotoView(user_mixins.LoggedInOnlyView, FormView):
    model = models.Photo
    template_name = "house/photo_create.html"
    fields = ("caption", "file")
    form_class = forms.CreatePhotoForm
    def form_valid(self, form):
        pk = self.kwargs.get("pk")
        form.save(pk)
        messages.success(self.request, "Photo has been uploaded")
        return redirect(reverse("houses:photos", kwargs={"pk": pk}))

@login_required
def delete_photo(request, house_pk, photo_pk):
    user = request.user 
    try:
        house = models.House.objects.get(pk=house_pk)
        if house.host.pk != user.pk: 
            messages.error(request, "You don't have permission to delete this photo")
        else:
            models.Photo.objects.filter(pk=photo_pk).delete() 
            messages.success(request, "Photo has been deleted") 
        return redirect(reverse("houses:photos", kwargs={"pk": house_pk}))
    except models.House.DoesNotExist: 
        return redirect(reverse("core:home"))

templates/house/house_create.html
{% extends "base.html" %}

{% block page_title %}
    Add house
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

        {% include 'mixins/house/house_form.html' with form=form cta="Add house" %}

    </div>
{% endblock content %}

templates/house/house_detail.html
{% extends "base.html" %}
{% load is_booked i18n %}
{% block page_title %}
    {{house.name}}
{% endblock page_title %}
{% block content %}
    <div class="-mt-5 container max-w-full h-75vh flex mb-20">
        <div class="h-full w-1/2 bg-center bg-cover" style="background-image:url({{house.first_photo}})"></div>
        <div class="h-full w-1/2 flex flex-wrap">
            {% for photo in house.get_next_four_photos %}
                <div style="background-image:url({{photo.file.url}})" class="w-1/2 h-auto bg-cover bg-center border-gray-700 border"></div>
            {% endfor %}
        </div>
    </div>
    <div class="container mx-auto flex justify-around pb-56">
        <div class="w-1/2">
            <div class="flex justify-between">
                <div class="mb-5">
                    <h4 class="text-3xl font-medium mb-px">{{house.name}}</h4>
                    <span class="text-gray-700 font-light">{{house.city}}</span>
                </div>
                <a href="{{house.host.get_absolute_url}}" class="flex flex-col items-center">
                    {% include "mixins/user_avatar.html" with user=house.host %}
                    <span class="mt-2 text-gray-500">{{house.host.first_name}}</span>
                </a>
            </div>
            {% comment %} {% on_favs house as on_favs_boolean %}
            {% if on_favs_boolean %}
                <a class="block mb-10 w-2/6 text-teal-600 font-bold" href="{% url 'lists:toggle-house' house.pk %}?action=remove">{% trans "Remove from Favourites" %}</a>
            {% else %}
                <a class="block mb-10 w-2/6 text-teal-600 font-bold" href="{% url 'lists:toggle-house' house.pk %}?action=add">{% trans "Save to Favourites" %}</a>
            {% endif %} {% endcomment %}
            <div class="flex border-section">
                <span class="mr-5 font-light">{{house.house_type}}</span>
                <span class="mr-5 font-light">{{house.bed}} bed{{house.bed|pluralize}}</span>
                <span class="mr-5 font-light">{{house.bathroom}} bath{{house.bathroom|pluralize}}</span>
                <span class="mr-5 font-light">{{house.guest}} guest{{house.guest|pluralize}}</span>
            </div>
            <p class="border-section">
                {{house.description}}
            </p>
            <div class="border-section">
                <h4 class="font-medium text-lg mb-5">Amenities</h4>
                {% for a in house.amenities.all %}
                    <li class="mb-2">{{a}}</li>
                {% endfor %}
            </div>
            <div class="border-section">
                <h4 class="font-medium text-lg mb-5">Facilities</h4>
                {% for a in house.facilities.all %}
                    <li class="mb-2">{{a}}</li>
                {% endfor %}
            </div>
            <div class="mt-10">
                <h4 class="font-medium text-2xl mb-5">Reviews</h4>
                <div class="flex items-center">
                    <div>
                        <i class="fas fa-star text-teal-500"></i>
                        <span class="font-bold text-xl">{{house.total_rating}}</span>
                    </div>
                    <div class="h-4 w-px bg-gray-400 mx-5"></div>
                    <div>
                        <span class="font-bold text-xl">{{house.reviews.count}}</span>
                        <span>review{{house.reviews.count|pluralize}}</span>
                    </div>
                </div>
                <div class="mt-10">
                    {% for review in house.reviews.all  %}
                        <div class="border-section">
                            <div class="mb-3 flex">
                                <div>
                                    {% include "mixins/user_avatar.html" with user=review.user h_and_w='w-10 h-10' text='text-xl' %}
                                </div>
                                <div class="flex flex-col ml-5">
                                    <span class="font-medium">{{review.user.first_name}}</span>
                                    <span class="text-sm text-gray-500">{{review.created|date:'F Y'}}</span>
                                </div>
                            </div>
                            <p>{{review.review}}</p>
                        </div>
                    {% endfor %}    
                </div>
            </div>
        </div>
        <div class="w-1/3">
            {% if house.host == user %}
                <a href="{% url 'houses:edit' house.pk %}" class="btn-link block">Edit house</a>
            {% else %}
                {% if not request.session.is_hosting %}
                    {% for calendar in house.get_calendars %}
                    <div class="mb-20">
                        <span class="text-center font-semibold text-lg block mb-8">{{calendar.get_month}}/{{calendar.year}}</span>
                        <div class="cal-grid font-medium  mb-4">
                        {% for day in calendar.day_names %}
                            <span>
                                {{day}}  
                            </span>
                        {% endfor %}
                        </div> 
                        <div class="cal-grid">
                            {% for day in calendar.get_days %}
                                {% is_booked house day as is_booked_bool %}
                                {% if day.number != 0 %}
                                    {% if day.past %}
                                    <span class="cal-number bg-gray-200 text-gray-400">{{day}}</span>
                                    {% elif is_booked_bool %}
                                    <span class="cal-number bg-gray-200 text-gray-400 line-through">{{day}}</span>
                                    {% else %}
                                    <a href="{% url 'reservations:create' house.pk day.year day.month day.number %}" class="cal-number bg-gray-200 text-gray-700 hover:bg-teal-400 hover:text-white hover:font-medium">{{day}}</a>
                                    {% endif %}
                                {% else %}
                                    <span></span>
                                {% endif %}
                            {% endfor %}
                        </div> 
                    </div>
                    {% endfor %}
                {% endif %} 
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/house/house_edit.html
{% extends "base.html" %}
{% block page_title %}
    Update house
{% endblock page_title %}
{% block search-bar %}
{% endblock search-bar %}
{% block content %}
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
        {% include 'mixins/house/house_form.html' with form=form cta="Update house" %} 
        <div class="mt-5"> 
            <a href="{% url 'houses:photos' house.pk %}" class="text-teal-500 font-medium">Edit Photos</a>
        </div>
    </div>
{% endblock content %}

templates/house/house_list.html
{% extends 'base.html' %}
    {%block page_title%}
        Home
    {%endblock page_title%}

    {%block content%}
        {% for house in object_list %}
            <h1>
                <a href="houses/{{house.pk}}"> Name: {{house.name}} -- Price: {{house.price}}$</a>
            </h1>
        {% endfor %}
        <h5>
            {% if page_obj.has_previous %}
                <a href="?page={{page_obj.previous_page_number}}">Prev</a>
            {% endif %}
            Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}
            {% if page_obj.has_next %}
                <a href="?page={{page_obj.next_page_number}}">Next</a>
            {% endif %}
        </h5>
        <h5> {{now}} </h5>
    {%endblock content%}

templates/house/house_photos.html
{% extends "base.html" %}
{% block page_title %}
    {{house.name}}'s Photos
{% endblock page_title %}
{% block search-bar %}
{% endblock search-bar %}
{% block content %}
    <div class="container mx-auto my-10 flex flex-col p-6">
        <div class="my-10 w-full">
            <a href="{% url 'houses:add-photos' house.pk %}" class="btn-link w-1/6 block">Upload photo</a>
        </div>
        {% for photo in house.photos.all %} 
            <div class="mb-5 border p-6 border-gray-400 flex justify-between">
                <div class="flex items-start">
                    <img src="{{photo.file.url}}" class="w-32 h-32"> 
                    <span class="ml-5 text-xl">{{photo.caption}}</span> 
                </div>
                <div class="flex flex-col w-1/5">
                    <a class="btn-link mb-5 bg-teal-500" href="#">Edit</a> 
                    <a class="btn-link bg-red-600" href="{% url 'houses:delete-photo' house.pk photo.pk %}">Delete</a>
                </div> 
            </div>    
        {% endfor %}
    </div>
{% endblock content %}

templates/house/photo_create.html
{% extends "base.html" %}
{% block page_title %}
    Upload photo
{% endblock page_title %}
{% block search-bar %}
{% endblock search-bar %}
{% block content %}
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
        {% include 'mixins/house/house_form.html' with form=form cta="Upload photo" %}
    </div>
{% endblock content %}

templates/house/search.html
{% extends "base.html" %}
    {% block page_title %}
        Search
    {% endblock page_title %}
    {% block search-bar %}
    {% endblock search-bar %}
    {% block content %}
    <h2>Search!</h2>
    <form method="get" action="{% url "houses:search" %}">
        {% comment %} <div>
            <label for="city">City</label>
            <input value="{{city}}" id="city" name="city" placeholder="Search by city" type="text">
        </div>
        <div>
            <label for="country">Country</label>
            <select id="country" name="country">
                <option value="" {% if s_countries == "" %}selected{% endif %}>
                    Any country
                </option>
                {% for country in countries %}
                    <option value="{{country.code}}" {% if  country.code == s_country %}selected{% endif %}>
                    {{country.name}}
                    </option>
                {% endfor %}
            </select>
        </div>
        {% comment %} <div>
            <label for="price">Price</label>
            <input value="{{price}}" id="price" name="price" placeholder="Search by price" type="text">
        </div> {% endcomment %}
        {% comment %} <div>
            <label for="house_type">House types</label>
            <select id="house_type" name="house_type">
                <option value="0" {% if s_house_type == 0 %}selected{% endif %}>
                    Any type
                </option>
                {% for house_type in house_types %}
                    <option value="{{house_type.pk}}" {% if s_house_type == house_type.pk %}selected{% endif %}>
                    {{house_type.name}}
                    </option>
                {% endfor %}
            </select>
        </div>
        <div>
            <h3>Amenities</h3>
            <ul>
                {% for amenity in amenities %}
                    <li>
                        <label for="a_{{amenity.pk}}">{{amenity.name}}</label>
                        <input
                        type="checkbox"
                        value="{{amenity.pk}}"
                        name="amenities"
                        id="a_{{amenity.pk}}"
                        {% if amenity.pk|slugify in s_amenities %}
                            checked 
                        {% endif %}
                        />                        
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div>
            <h3>Facilities</h3>
            <ul>
                {% for facility in facilities %}
                    <li>
                        <label for="f_{{facility.pk}}">{{facility.name}}</label>
                        <input
                        type="checkbox"
                        value="{{facility.pk}}"
                        name="facilities"
                        id="f_{{facility.pk}}"
                        {% if facility.pk|slugify in s_facilities %}
                            checked
                        {% endif %}                          
                        />                        
                    </li>
                {% endfor %}
            </ul>
        </div> {% endcomment %}
            {{form}}
        <button>Search</button>
        <h3>Results</h3>
        {%for house in houses%}
            <h4>{{house.name}}</h4>
        {%endfor%}
    </form>
    {% endblock content %}