core/urls.py
from django.urls import path
from house import views as house_views

app_name = "core"
urlpatterns = [
    path("", house_views.HomeView.as_view(), name="home"),
    # path("", house_views.all_houses)
]

landbnb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("admin/", admin.site.urls),
    path("users/", include("users.urls", namespace="users")),
    path("houses/", include("house.urls", namespace="houses")),
    path("reservations/", include("reservation.urls", namespace="reservations")),
    path("reviews/", include("review.urls", namespace="reviews")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include
from . import views

app_name = "users"
urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github/", views.github_login, name="github-login"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
    path("switch-hosting/", views.switch_hosting, name="switch-hosting"),
    # path("verify/<str:key>", views.complete_verification, name="complete-verification"),
]

users/models.py
from django.contrib.auth.models import AbstractUser 
from django.shortcuts import reverse
from django.db import models
from core import managers as core_managers

class User(AbstractUser):
    GENDER_MALE = "male"
    GENDER_FEMALE = "female"
    GENDER_CHOICES = (
        (GENDER_MALE, "Male"),
        (GENDER_FEMALE, "Female"),
    )

    LANGUAGE_ENGLISH = "en"
    LANGUAGE_VIETNAMESE = "vi"
    LANGUAGE_CHOICES = (
        (LANGUAGE_ENGLISH, "English"),
        (LANGUAGE_VIETNAMESE, "Vietnamese"),
    )

    LOGIN_EMAIL = "email"

    avatar = models.ImageField(null=True, blank=True)
    gender = models.CharField(choices=GENDER_CHOICES, max_length=10, null=True, blank=True)
    language = models.CharField(choices=LANGUAGE_CHOICES, max_length=2)
    birthday = models.DateField(null=True)
    superhost = models.BooleanField(default=False)
    bio = models.TextField(default="", blank=True)

    # objects = core_managers.CustomModelManager()

    def get_absolute_url(self):
        return reverse("users:profile", kwargs={"pk": self.pk})

    pass

users/forms.py
from django import forms
from . import models

class LoginForm(forms.Form):
    """Login Form Definition"""

    email = forms.EmailField(widget=forms.EmailInput(attrs={"placeholder": "Email"}))
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Password"})
    )

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        try:
            user = models.User.objects.get(email=email)
            if user.check_password(password):
                return self.cleaned_data
            else:
                self.add_error("password", forms.ValidationError("Password is wrong"))
        except models.User.DoesNotExist:
            self.add_error("email", forms.ValidationError("User does not exist"))


class SignUpForm(forms.ModelForm):
    class Meta:
        model = models.User
        fields = ("first_name", "last_name", "email")
        widgets = {
            "first_name": forms.TextInput(attrs={"placeholder": "First Name"}),
            "last_name": forms.TextInput(attrs={"placeholder": "Last Name"}),
            "email": forms.EmailInput(attrs={"placeholder": "Email Name"}),
        }

    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Password"})
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Confirm Password"}),
        label="Confirm password"
    )

    def clean_email(self):
        email = self.cleaned_data.get("email")
        try:
            models.User.objects.get(email=email)
            raise forms.ValidationError(
                "That email is already taken", code="existing_user"
            )
        except models.User.DoesNotExist:
            return email

    def clean_password1(self):
        password = self.cleaned_data.get("password")
        password1 = self.cleaned_data.get("password1")

        if password != password1:
            raise forms.ValidationError("Password confirmation does not match")
        else:
            return password

    def save(self, *args, **kwargs):
        user = super().save(commit=False)
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        user.username = email
        user.set_password(password)
        user.save()

users/views.py
from django.views.generic import FormView, DetailView, UpdateView
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.views import PasswordChangeView 
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from . import models, forms, mixin
# Create your views here.

class UserProfileView(DetailView):
    model = models.User
    context_object_name = "user_obj"

    pass

class UpdateProfileView(mixin.LoggedInOnlyView, SuccessMessageMixin, UpdateView): 
    model = models.User
    template_name = "users/update-profile.html" 
    fields = (     
        "first_name",
        "last_name",
        "gender",
        "avatar",
        "bio",
        "birthday",
        "language",
    )
    success_message = "Profile has been updated"

    def get_object(self, queryset=None):
        return self.request.user

    def get_form(self):
        form = super().get_form()
        form.fields["first_name"].widget.attrs = {"placeholder": "First name"}
        form.fields["last_name"].widget.attrs = {"placeholder": "Last name"}
        form.fields["gender"].widget.attrs = {"placeholder": "Gender"}
        form.fields["bio"].widget.attrs = {"placeholder": "bio"}
        form.fields["birthday"].widget.attrs = {"placeholder": "Birthdate"}
        form.fields["language"].widget.attrs = {"placeholder": "Language"}
        return form

class UpdatePasswordView(mixin.LoggedInOnlyView, SuccessMessageMixin, PasswordChangeView):
    template_name = "users/update-password.html"
    success_message = "Password has been updated"

    def get_form(self):
        form = super().get_form()
        form.fields["old_password"].widget.attrs = {"placeholder": "Current password"}
        form.fields["new_password1"].widget.attrs = {"placeholder": "New password"}
        form.fields["new_password2"].widget.attrs = {"placeholder": "Confirm new password"}
        return form

    def get_success_url(self): 
        return self.request.user.get_absolute_url()

class LoginView(mixin.LoggedOutOnlyView, FormView):
    template_name = "users/login.html"
    form_class = forms.LoginForm
    success_url = reverse_lazy("core:home")

    def form_valid(self, form):
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)

        if user is not None:
            messages.info(self.request, f"Login succesfully")
            login(self.request, user)
        return super().form_valid(form)

class SignUpView(mixin.LoggedOutOnlyView, FormView): 
    template_name = "users/signup.html"
    form_class = forms.SignUpForm
    success_url = reverse_lazy("core:home") 
    initial = {
        "first_name": "Khang",
        "last_name": "Phan",
        "email": "khang@test.com",
    }

    def form_valid(self, form): 
        form.save() 
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            messages.info(self.request, f"Register succesfully")
            login(self.request, user)
        return super().form_valid(form)

def log_out(request):
    logout(request)
    messages.info(request, f"See you later")
    return redirect(reverse("core:home"))

@login_required
def switch_hosting(request):
    try:
        del request.session["is_hosting"] 
    except KeyError:
        request.session["is_hosting"] = True 
    return redirect(reverse("core:home"))

def github_login(request):
    pass

templates/users/login.html
{% extends "base.html" %}
{% block page_title %}
    Login
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
        {% include 'mixins/auth/auth_form.html' with form=form cta="Log in" %}
        
        <div class="mt-5">
            <span class="mr-2">Ya need an account?</span>
            <a href="{% url 'users:signup' %}" class="text-teal-500 font-medium">Register</a>
        </div>
    </div>
{% endblock content %}

templates/users/signup.html
{% extends "base.html" %}
    {% block page_title %}
        Register
    {% endblock page_title %}

    {% block search-bar %}
    {% endblock search-bar %}

    {% block content %}
        <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
            {% include 'mixins/auth/auth_form.html' with form=form cta="Sign up" %}

            <div class="mt-5">
                <span class="mr-2">Ya already had an account?</span>
                <a href="{% url 'users:login' %}" class="text-teal-500 font-medium">Login</a>
            </div>
        </div>
    {% endblock content %}

templates/users/update-password.html
{% extends "base.html" %}

{% block page_title %}
    Update Password
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

<div class="min-h-75vh">
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
            {% include 'mixins/auth/auth_form.html' with form=form cta="Update Password" %}
    </div>
</div>
{% endblock content %}

templates/users/update-profile.html
{% extends "base.html" %}
{% block page_title %}
    Update Profile
{% endblock page_title %}
{% block search-bar %} 
{% endblock search-bar %}
{% block content %}
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
        {% include 'mixins/auth/auth_form.html' with form=form cta="Update Profile" %}
        <div class="mt-5">
            <a href="{% url 'users:password' %}" class="text-teal-500 font-medium">Change Password</a>
        </div>
    </div>
{% endblock content %}

{% comment %} {% extends "base.html" %}
{% block page_title %}
    Update Profile
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
        
        {% include 'mixins/auth/auth_form.html' with form=form cta="Update Profile" %}
        
        {% if object.login_method == "email" %}
        <div class="mt-5">
            <a href="{% url 'users:password' %}" class="text-teal-500 font-medium">Change Password</a>
        </div>
        {% endif %}
    </div>
{% endblock content %} {% endcomment %}

templates/users/user_detail.html
{% extends "base.html" %}
{% block page_title %}
    {{user_obj.first_name}}'s Profile
{% endblock page_title %}
{% block content %}
<div class="h-75vh">
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400 ove">
        {% include "mixins/user_avatar.html" with user=user_obj %}
        <div class="flex items-center">
            <span class="text-3xl mt-1">{{user_obj.first_name}}</span>
            {% if user_obj.superhost %}
                <i class="fas fa-check-circle text-teal-400 ml-1"></i>
            {% endif %}
        </div>
        <span class="text-lg mb-5">{{user.bio}}</span>
        {% if user == user_obj %}
        <a href="{% url 'users:update' %}" class="btn-link">Edit Profile</a>
        {% endif %}        
    </div>
    {% if user_obj.houses.count > 0 %}
    <div class="container mx-auto pb-10 flex flex-col items-center">
        <h3 class="mb-12 text-2xl">{{user_obj.first_name}}'s Houses</h3>
        <div class="flex flex-wrap -mx-40 mb-10">
            {% for house in user_obj.houses.all  %}
                {% include 'mixins/house_card.html' with house=house %}
            {% endfor %}
        </div>
    </div>
    {% endif %}
</div>
{% endblock content %}